// Dishes suggested for a restaurant by cuisine when its real menu isn't
// available. Each name has an example photo in assets/dishes (see
// scripts/fetch-dish-photos.ts and server/dish-photos.json).

export const CUISINE_DISHES: Record<string, { name: string; desc: string }[]> = {
  Italian: [
    { name: "Margherita Pizza", desc: "Wood-fired crust, San Marzano tomato, fresh mozzarella, basil" },
    { name: "Pasta Carbonara", desc: "Spaghetti, guanciale, pecorino romano, egg yolk, black pepper" },
    { name: "Chicken Parmigiana", desc: "Breaded cutlet, marinara, melted mozzarella, fresh basil" },
    { name: "Risotto ai Funghi", desc: "Arborio rice, wild mushrooms, parmesan, white truffle oil" },
    { name: "Osso Buco", desc: "Braised veal shanks, gremolata, saffron risotto" },
  ],
  Chinese: [
    { name: "Kung Pao Chicken", desc: "Wok-tossed chicken, peanuts, dried chilis, Sichuan peppercorn" },
    { name: "Peking Duck", desc: "Crispy roasted duck, hoisin sauce, scallion, thin pancakes" },
    { name: "Mapo Tofu", desc: "Silken tofu, spicy chili bean paste, minced pork, Sichuan pepper" },
    { name: "Dim Sum Platter", desc: "Har gow, siu mai, char siu bao, steamed to order" },
    { name: "Dan Dan Noodles", desc: "Spicy sesame noodles, ground pork, chili oil, pickled mustard greens" },
  ],
  Japanese: [
    { name: "Salmon Sashimi", desc: "Premium fresh-cut salmon, soy, pickled ginger, wasabi" },
    { name: "Tonkotsu Ramen", desc: "Rich pork bone broth, chashu, soft-boiled egg, nori, scallions" },
    { name: "Chicken Katsu Curry", desc: "Crispy panko chicken, Japanese curry, steamed rice, pickles" },
    { name: "Dragon Roll", desc: "Shrimp tempura, avocado, eel sauce, spicy mayo, tobiko" },
    { name: "Wagyu Beef Don", desc: "Seared A5 wagyu slices, seasoned rice, onsen egg, truffle soy" },
  ],
  Mexican: [
    { name: "Birria Tacos", desc: "Slow-braised beef, consommé dip, cilantro, onion, corn tortilla" },
    { name: "Carne Asada Burrito", desc: "Grilled steak, guacamole, pico de gallo, rice, cheese, flour tortilla" },
    { name: "Enchiladas Suizas", desc: "Chicken enchiladas, tomatillo cream sauce, queso fresco, sour cream" },
    { name: "Fish Tacos", desc: "Beer-battered fish, chipotle slaw, lime crema, pickled onion" },
    { name: "Chile Relleno", desc: "Roasted poblano, melted cheese, ranchero sauce, rice and beans" },
  ],
  Indian: [
    { name: "Butter Chicken", desc: "Tender chicken in creamy tomato gravy, aromatic spices, naan" },
    { name: "Lamb Biryani", desc: "Fragrant basmati, slow-cooked lamb, saffron, fried onions, raita" },
    { name: "Palak Paneer", desc: "Creamy spinach curry, paneer cubes, cumin, garlic, garam masala" },
    { name: "Tandoori Platter", desc: "Tandoori chicken, seekh kebab, naan, mint chutney, onion salad" },
    { name: "Chana Masala", desc: "Spiced chickpea curry, tomato, ginger, cumin, cilantro, basmati rice" },
  ],
  Thai: [
    { name: "Pad Thai", desc: "Rice noodles, prawns, peanuts, bean sprouts, tamarind, lime" },
    { name: "Green Curry", desc: "Coconut milk, Thai basil, bamboo shoots, bell pepper, jasmine rice" },
    { name: "Tom Yum Soup", desc: "Hot & sour broth, shrimp, lemongrass, galangal, kaffir lime" },
    { name: "Mango Sticky Rice", desc: "Sweet coconut sticky rice, fresh mango, toasted sesame" },
    { name: "Massaman Curry", desc: "Rich peanut curry, tender beef, potato, roasted cashews" },
  ],
  French: [
    { name: "Duck Confit", desc: "Slow-cooked duck leg, cherry gastrique, pomme purée" },
    { name: "Coq au Vin", desc: "Braised chicken, red wine, pearl onions, mushrooms, lardons" },
    { name: "Steak Frites", desc: "Pan-seared bavette, shoestring fries, béarnaise, green salad" },
    { name: "French Onion Soup", desc: "Caramelized onion broth, gruyère crouton, fresh thyme" },
    { name: "Crème Brûlée", desc: "Vanilla bean custard, caramelized sugar crust, fresh berries" },
  ],
  Korean: [
    { name: "Korean BBQ Platter", desc: "Bulgogi, galbi, banchan, lettuce wraps, ssamjang" },
    { name: "Bibimbap", desc: "Mixed rice bowl, gochujang, fried egg, vegetables, sesame oil" },
    { name: "Tteokbokki", desc: "Spicy rice cakes, fish cakes, scallion, sweet chili glaze" },
    { name: "Kimchi Jjigae", desc: "Fermented kimchi stew, pork belly, tofu, scallion, steamed rice" },
    { name: "Japchae", desc: "Glass noodles, sesame, mixed vegetables, soy, toasted sesame" },
  ],
  American: [
    { name: "Smash Burger", desc: "Double smashed patties, American cheese, pickles, special sauce" },
    { name: "Nashville Hot Chicken", desc: "Spicy fried chicken, coleslaw, bread and butter pickles" },
    { name: "BBQ Ribs", desc: "St. Louis-style, house-smoked, tangy BBQ glaze, cornbread" },
    { name: "Mac & Cheese", desc: "Four-cheese blend, crispy breadcrumb crust, truffle oil" },
    { name: "Philly Cheesesteak", desc: "Shaved ribeye, melted provolone, peppers, onions, hoagie roll" },
    { name: "Chicken Tenders", desc: "Hand-breaded tenders, fries, honey mustard" },
    { name: "Cobb Salad", desc: "Chicken, bacon, egg, avocado, blue cheese, tomato" },
    { name: "Meatloaf", desc: "Glazed meatloaf, mashed potatoes, gravy, green beans" },
    { name: "Chicken Fried Steak", desc: "Crispy breaded steak, country gravy, mashed potatoes" },
    { name: "Buffalo Wings", desc: "Crispy wings, buffalo sauce, celery, blue cheese" },
    { name: "Pot Roast", desc: "Slow-braised beef, carrots, potatoes, pan gravy" },
    { name: "Reuben Sandwich", desc: "Corned beef, sauerkraut, Swiss, Russian dressing, rye" },
  ],
  Mediterranean: [
    { name: "Lamb Shawarma", desc: "Slow-roasted lamb, tahini, pickled turnip, pita, hummus" },
    { name: "Falafel Platter", desc: "Crispy chickpea falafel, hummus, tabbouleh, pickles, pita" },
    { name: "Grilled Sea Bass", desc: "Mediterranean herbs, lemon, olive oil, roasted vegetables" },
    { name: "Mezze Board", desc: "Hummus, baba ganoush, labneh, olives, warm pita, feta" },
    { name: "Kebab Platter", desc: "Mixed grilled meats, saffron rice, grilled tomato, sumac onion" },
  ],
  Seafood: [
    { name: "Lobster Roll", desc: "Fresh Maine lobster, butter, lemon, toasted split-top bun" },
    { name: "Fish & Chips", desc: "Beer-battered cod, thick-cut fries, mushy peas, tartar sauce" },
    { name: "Grilled Salmon", desc: "Atlantic salmon, lemon dill sauce, asparagus, wild rice" },
    { name: "Shrimp Scampi", desc: "Garlic butter shrimp, white wine, linguine, fresh parsley" },
    { name: "Crab Cakes", desc: "Jumbo lump crab, Old Bay, remoulade, mixed greens" },
  ],
  Vietnamese: [
    { name: "Pho Bo", desc: "Rich beef broth, rice noodles, rare steak, herbs, bean sprouts" },
    { name: "Banh Mi", desc: "Crispy baguette, lemongrass pork, pickled daikon, cilantro, jalapeño" },
    { name: "Bun Bo Hue", desc: "Spicy beef noodle soup, lemongrass, shrimp paste, herbs" },
    { name: "Spring Rolls", desc: "Fresh rice paper, shrimp, vermicelli, herbs, peanut dipping sauce" },
  ],
  Greek: [
    { name: "Souvlaki Platter", desc: "Grilled pork skewers, tzatziki, pita, tomato, onion, fries" },
    { name: "Moussaka", desc: "Layered eggplant, spiced lamb, béchamel, baked golden" },
    { name: "Greek Salad", desc: "Tomato, cucumber, feta, kalamata olives, oregano, olive oil" },
    { name: "Lamb Gyro", desc: "Seasoned lamb, tzatziki, lettuce, tomato, warm pita" },
  ],
  Burgers: [
    { name: "Classic Cheeseburger", desc: "Beef patty, American cheese, lettuce, tomato, pickles, brioche" },
    { name: "Bacon BBQ Burger", desc: "Angus beef, crispy bacon, cheddar, onion ring, BBQ sauce" },
    { name: "Mushroom Swiss Burger", desc: "Sautéed mushrooms, melted Swiss, garlic aioli, toasted bun" },
  ],
  Pizza: [
    { name: "Pepperoni Pizza", desc: "Classic pepperoni, mozzarella, house marinara, crispy crust" },
    { name: "Margherita Pizza", desc: "San Marzano tomato, fresh mozzarella, basil, olive oil" },
    { name: "Meat Lovers Pizza", desc: "Pepperoni, sausage, bacon, ham, mozzarella, red sauce" },
  ],
  Sushi: [
    { name: "Omakase Selection", desc: "Chef's choice of premium nigiri, sashimi, and special rolls" },
    { name: "Spicy Tuna Roll", desc: "Fresh tuna, spicy mayo, cucumber, sesame, crispy tempura flakes" },
    { name: "Rainbow Roll", desc: "California roll topped with salmon, tuna, yellowtail, avocado" },
  ],
  BBQ: [
    { name: "Smoked Brisket", desc: "12-hour oak-smoked, pepper crust, house pickles, white bread" },
    { name: "Pulled Pork Sandwich", desc: "Slow-smoked pork, vinegar slaw, brioche bun, pickle chips" },
    { name: "Smoked Wings", desc: "Hickory-smoked, Alabama white sauce, celery, blue cheese" },
  ],
  Steakhouse: [
    { name: "Ribeye Steak", desc: "16oz bone-in ribeye, herb butter, roasted garlic, creamed spinach" },
    { name: "Filet Mignon", desc: "8oz center-cut, peppercorn sauce, truffle mashed potato" },
    { name: "Tomahawk Steak", desc: "32oz long-bone ribeye, charred, compound butter, roasted veg" },
  ],
  Cafe: [
    { name: "Avocado Toast", desc: "Sourdough, smashed avocado, poached eggs, chili flakes, microgreens" },
    { name: "Eggs Benedict", desc: "Poached eggs, Canadian bacon, hollandaise, English muffin" },
    { name: "Acai Bowl", desc: "Acai blend, granola, banana, berries, honey, coconut flakes" },
  ],
  Breakfast: [
    { name: "Pancake Stack", desc: "Fluffy buttermilk pancakes, maple syrup, butter, fresh berries" },
    { name: "Eggs Benedict", desc: "Poached eggs, hollandaise, Canadian bacon, English muffin, hash browns" },
    { name: "Breakfast Burrito", desc: "Scrambled eggs, chorizo, cheese, avocado, salsa, flour tortilla" },
  ],
  Brunch: [
    { name: "French Toast", desc: "Thick brioche, vanilla custard, berries, maple syrup, whipped cream" },
    { name: "Shakshuka", desc: "Poached eggs, spiced tomato sauce, feta, herbs, crusty bread" },
    { name: "Chicken & Waffles", desc: "Crispy fried chicken, Belgian waffle, hot honey, maple butter" },
  ],
  Turkish: [
    { name: "Iskender Kebab", desc: "Sliced doner, tomato sauce, yogurt, butter, warm pide bread" },
    { name: "Lahmacun", desc: "Crispy flatbread, spiced lamb, parsley, lemon, onion" },
    { name: "Mixed Grill Platter", desc: "Adana kebab, chicken shish, köfte, rice, grilled vegetables" },
  ],
  Ramen: [
    { name: "Tonkotsu Ramen", desc: "Rich pork bone broth, chashu pork, soft egg, nori, scallion" },
    { name: "Miso Ramen", desc: "Fermented soybean broth, corn, butter, bean sprouts, ground pork" },
    { name: "Spicy Tantanmen", desc: "Sesame chili broth, ground pork, bok choy, soft egg, chili oil" },
  ],
  Coffee: [
    { name: "Latte & Pastry", desc: "House espresso latte, fresh-baked croissant, seasonal jam" },
    { name: "Cold Brew Float", desc: "Nitro cold brew, vanilla bean ice cream, chocolate drizzle" },
    { name: "Breakfast Sandwich", desc: "Egg, bacon, cheddar, arugula, house-made aioli, ciabatta" },
  ],
  Bakery: [
    { name: "Fresh Croissant Plate", desc: "Butter croissant, jam trio, whipped butter, fresh fruit" },
    { name: "Artisan Bread Board", desc: "Sourdough, focaccia, olive oil, balsamic, whipped ricotta" },
    { name: "Quiche Lorraine", desc: "Flaky pastry, bacon, gruyère, caramelized onion, side salad" },
  ],
  "Ice Cream": [
    { name: "Sundae Supreme", desc: "Three scoops, hot fudge, caramel, whipped cream, cherry" },
    { name: "Waffle Cone Duo", desc: "Two premium scoops, fresh waffle cone, sprinkles" },
    { name: "Banana Split", desc: "Banana, three scoops, chocolate, strawberry, pineapple, nuts" },
  ],
  Sandwiches: [
    { name: "Club Sandwich", desc: "Turkey, bacon, lettuce, tomato, mayo, toasted sourdough" },
    { name: "Italian Sub", desc: "Prosciutto, salami, capicola, provolone, peppers, oil & vinegar" },
    { name: "Grilled Cheese Deluxe", desc: "Three-cheese blend, tomato soup, sourdough, truffle oil" },
  ],
  Vegetarian: [
    { name: "Buddha Bowl", desc: "Quinoa, roasted vegetables, tahini, avocado, pickled onion" },
    { name: "Veggie Burger", desc: "Black bean patty, avocado, sprouts, chipotle aioli, brioche" },
    { name: "Stuffed Bell Peppers", desc: "Rice, black beans, corn, cheese, tomato sauce, cilantro" },
  ],
  Vegan: [
    { name: "Impossible Burger", desc: "Plant-based patty, vegan cheese, lettuce, tomato, special sauce" },
    { name: "Cauliflower Steak", desc: "Roasted cauliflower, chimichurri, quinoa, roasted vegetables" },
    { name: "Jackfruit Tacos", desc: "Pulled jackfruit, slaw, avocado crema, pickled onion, corn tortilla" },
  ],
};
