export type SessionMode = "dine-out" | "cook-in";

export interface GroundedSource {
  title: string;
  uri: string;
}

export interface Dish {
  id: string;
  name: string;
  restaurant: string;
  cuisine: string;
  description: string;
  image: string;
  price: string;
  rating?: number;
  address?: string;
  placeId?: string;
  photoAuthors?: string[];
  // True when the dish name is inferred from cuisine, not the restaurant's menu.
  suggested?: boolean;
  // True when there is no dish to suggest (fast food, or a cuisine we have no
  // dishes for): the card is the restaurant itself and `name` is its name.
  restaurantOnly?: boolean;
  ratingCount?: number;
  // Places details for the match screen's actions.
  mapsUrl?: string;
  phone?: string;
  website?: string;
  // Set when the dish came from Gemini Maps grounding; these Google Maps links
  // must be shown right after the dish (Google's grounding terms).
  groundedSources?: GroundedSource[];
  cookTime?: string;
  servings?: string;
  difficulty?: string;
  mode?: SessionMode;
}

export const DISHES: Dish[] = [
  {
    id: "d1",
    name: "Truffle Margherita",
    restaurant: "Bella Napoli",
    cuisine: "Italian",
    description: "Wood-fired crust, San Marzano tomato, fresh mozzarella, black truffle shavings",
    image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=800&q=80",
    price: "$22",
    mode: "dine-out",
  },
  {
    id: "d2",
    name: "Wagyu Burger",
    restaurant: "The Grill House",
    cuisine: "American",
    description: "A5 Wagyu beef patty, aged cheddar, caramelized onions, truffle aioli, brioche bun",
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&q=80",
    price: "$28",
    mode: "dine-out",
  },
  {
    id: "d3",
    name: "Salmon Sashimi Platter",
    restaurant: "Sakura Japanese",
    cuisine: "Japanese",
    description: "Premium Atlantic salmon, soy glaze, pickled ginger, wasabi, cucumber rolls",
    image: "https://images.unsplash.com/photo-1580822184713-fc5400e7fe10?w=800&q=80",
    price: "$32",
    mode: "dine-out",
  },
  {
    id: "d4",
    name: "Spicy Pad Thai",
    restaurant: "Bangkok Street",
    cuisine: "Thai",
    description: "Rice noodles, tiger prawns, bean sprouts, peanuts, tamarind sauce, lime",
    image: "https://images.unsplash.com/photo-1559314809-0d155014e29e?w=800&q=80",
    price: "$18",
    mode: "dine-out",
  },
  {
    id: "d5",
    name: "Lamb Shawarma Bowl",
    restaurant: "Zara Mediterranean",
    cuisine: "Mediterranean",
    description: "Slow-roasted lamb, saffron rice, hummus, tzatziki, pickled cabbage",
    image: "https://images.unsplash.com/photo-1541014741259-de529411b96a?w=800&q=80",
    price: "$20",
    mode: "dine-out",
  },
  {
    id: "d6",
    name: "Lobster Bisque",
    restaurant: "Harbor & Co.",
    cuisine: "Seafood",
    description: "Maine lobster, cream, sherry, tarragon oil, toasted sourdough croutons",
    image: "https://images.unsplash.com/photo-1547592180-85f173990554?w=800&q=80",
    price: "$24",
    mode: "dine-out",
  },
  {
    id: "d7",
    name: "Mushroom Ramen",
    restaurant: "Noodle Lab",
    cuisine: "Japanese",
    description: "Rich porcini broth, silky noodles, soft-boiled egg, crispy tofu, scallions",
    image: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=800&q=80",
    price: "$17",
    mode: "dine-out",
  },
  {
    id: "d8",
    name: "BBQ Brisket Tacos",
    restaurant: "Smoke & Barrel",
    cuisine: "Mexican",
    description: "12-hour smoked brisket, pickled jalapeño, cotija cheese, cilantro, corn tortillas",
    image: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=800&q=80",
    price: "$16",
    mode: "dine-out",
  },
  {
    id: "d9",
    name: "Butter Chicken",
    restaurant: "Spice Route",
    cuisine: "Indian",
    description: "Tender chicken in creamy tomato gravy, aromatic spices, garlic naan",
    image: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=800&q=80",
    price: "$19",
    mode: "dine-out",
  },
  {
    id: "d10",
    name: "Avocado Toast Deluxe",
    restaurant: "Green Bowl Cafe",
    cuisine: "Brunch",
    description: "Sourdough, smashed avocado, poached eggs, everything bagel seasoning, microgreens",
    image: "https://images.unsplash.com/photo-1525351484163-7529414344d8?w=800&q=80",
    price: "$15",
    mode: "dine-out",
  },
  {
    id: "d11",
    name: "Duck Confit",
    restaurant: "Maison Française",
    cuisine: "French",
    description: "Slow-cooked duck leg, cherry gastrique, pomme purée, haricots verts",
    image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80",
    price: "$36",
    mode: "dine-out",
  },
  {
    id: "d12",
    name: "Ceviche Tostada",
    restaurant: "La Playa",
    cuisine: "Mexican",
    description: "Fresh sea bass, citrus cure, mango, red onion, avocado cream, crispy tostada",
    image: "https://images.unsplash.com/photo-1626645738196-c2a7c87a8f58?w=800&q=80",
    price: "$14",
    mode: "dine-out",
  },
  {
    id: "d13",
    name: "Pepperoni Deep Dish",
    restaurant: "Chicago Style Co.",
    cuisine: "Italian",
    description: "Thick crust loaded with pepperoni, mozzarella, house marinara, Italian sausage",
    image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800&q=80",
    price: "$26",
    mode: "dine-out",
  },
  {
    id: "d14",
    name: "Prawn Laksa",
    restaurant: "Singapore Kitchen",
    cuisine: "Asian",
    description: "Coconut curry broth, fat prawns, rice noodles, tofu puffs, sambal",
    image: "https://images.unsplash.com/photo-1617093727343-374698b1b08d?w=800&q=80",
    price: "$21",
    mode: "dine-out",
  },
  {
    id: "d15",
    name: "Steak Frites",
    restaurant: "The Grill House",
    cuisine: "American",
    description: "8oz ribeye, crispy shoestring fries, compound butter, red wine jus",
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?w=800&q=80",
    price: "$42",
    mode: "dine-out",
  },
];

export const RECIPES: Dish[] = [
  {
    id: "r1",
    name: "Creamy Garlic Tuscan Chicken",
    restaurant: "Home Kitchen",
    cuisine: "Italian",
    description: "Pan-seared chicken thighs in a sun-dried tomato, spinach & parmesan cream sauce",
    image: "https://images.unsplash.com/photo-1532550907401-a500c9a57435?w=800&q=80",
    price: "$12",
    cookTime: "35 min",
    servings: "4",
    difficulty: "Easy",
    mode: "cook-in",
  },
  {
    id: "r2",
    name: "Homemade Ramen",
    restaurant: "Home Kitchen",
    cuisine: "Japanese",
    description: "Rich miso broth, fresh noodles, soft-boiled egg, chashu pork, corn, nori",
    image: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=800&q=80",
    price: "$8",
    cookTime: "45 min",
    servings: "4",
    difficulty: "Medium",
    mode: "cook-in",
  },
  {
    id: "r3",
    name: "One-Pan Lemon Herb Salmon",
    restaurant: "Home Kitchen",
    cuisine: "Seafood",
    description: "Baked salmon fillet, lemon butter, asparagus, cherry tomatoes, fresh dill",
    image: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800&q=80",
    price: "$14",
    cookTime: "25 min",
    servings: "2",
    difficulty: "Easy",
    mode: "cook-in",
  },
  {
    id: "r4",
    name: "Chicken Tikka Masala",
    restaurant: "Home Kitchen",
    cuisine: "Indian",
    description: "Marinated chicken in rich tomato-cream curry, garam masala, basmati rice, naan",
    image: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=800&q=80",
    price: "$10",
    cookTime: "50 min",
    servings: "4",
    difficulty: "Medium",
    mode: "cook-in",
  },
  {
    id: "r5",
    name: "Classic Carbonara",
    restaurant: "Home Kitchen",
    cuisine: "Italian",
    description: "Spaghetti, guanciale, pecorino romano, egg yolks, cracked black pepper",
    image: "https://images.unsplash.com/photo-1612874742237-6526221588e3?w=800&q=80",
    price: "$7",
    cookTime: "20 min",
    servings: "4",
    difficulty: "Easy",
    mode: "cook-in",
  },
  {
    id: "r6",
    name: "Beef Stir-Fry",
    restaurant: "Home Kitchen",
    cuisine: "Chinese",
    description: "Sliced beef, bell peppers, broccoli, soy-ginger glaze, steamed jasmine rice",
    image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=800&q=80",
    price: "$9",
    cookTime: "20 min",
    servings: "3",
    difficulty: "Easy",
    mode: "cook-in",
  },
  {
    id: "r7",
    name: "Homemade Margherita Pizza",
    restaurant: "Home Kitchen",
    cuisine: "Italian",
    description: "Hand-stretched dough, San Marzano sauce, fresh mozzarella, basil, olive oil",
    image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=800&q=80",
    price: "$6",
    cookTime: "30 min",
    servings: "4",
    difficulty: "Medium",
    mode: "cook-in",
  },
  {
    id: "r8",
    name: "Thai Green Curry",
    restaurant: "Home Kitchen",
    cuisine: "Thai",
    description: "Coconut milk, green curry paste, chicken, bamboo shoots, Thai basil, jasmine rice",
    image: "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=800&q=80",
    price: "$8",
    cookTime: "30 min",
    servings: "4",
    difficulty: "Easy",
    mode: "cook-in",
  },
  {
    id: "r9",
    name: "Smash Burgers",
    restaurant: "Home Kitchen",
    cuisine: "American",
    description: "Double-smashed beef patties, American cheese, pickles, special sauce, brioche bun",
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&q=80",
    price: "$8",
    cookTime: "15 min",
    servings: "4",
    difficulty: "Easy",
    mode: "cook-in",
  },
  {
    id: "r10",
    name: "Shrimp Scampi Linguine",
    restaurant: "Home Kitchen",
    cuisine: "Italian",
    description: "Garlic butter shrimp, white wine, lemon, red pepper flakes, fresh parsley",
    image: "https://images.unsplash.com/photo-1563379926898-05f4575a45d8?w=800&q=80",
    price: "$12",
    cookTime: "20 min",
    servings: "3",
    difficulty: "Easy",
    mode: "cook-in",
  },
  {
    id: "r11",
    name: "Korean Bibimbap",
    restaurant: "Home Kitchen",
    cuisine: "Korean",
    description: "Rice bowl, gochujang, fried egg, sautéed vegetables, pickled radish, sesame",
    image: "https://images.unsplash.com/photo-1553163147-622ab57be1c7?w=800&q=80",
    price: "$7",
    cookTime: "35 min",
    servings: "2",
    difficulty: "Medium",
    mode: "cook-in",
  },
  {
    id: "r12",
    name: "Chicken Fajitas",
    restaurant: "Home Kitchen",
    cuisine: "Mexican",
    description: "Sizzling chicken, bell peppers, onions, guacamole, sour cream, warm tortillas",
    image: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=800&q=80",
    price: "$9",
    cookTime: "25 min",
    servings: "4",
    difficulty: "Easy",
    mode: "cook-in",
  },
  {
    id: "r13",
    name: "Mushroom Risotto",
    restaurant: "Home Kitchen",
    cuisine: "Italian",
    description: "Arborio rice, mixed mushrooms, white wine, parmesan, butter, fresh thyme",
    image: "https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=800&q=80",
    price: "$8",
    cookTime: "40 min",
    servings: "4",
    difficulty: "Medium",
    mode: "cook-in",
  },
  {
    id: "r14",
    name: "Fish Tacos",
    restaurant: "Home Kitchen",
    cuisine: "Mexican",
    description: "Beer-battered cod, chipotle slaw, lime crema, pickled onion, corn tortillas",
    image: "https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=800&q=80",
    price: "$10",
    cookTime: "25 min",
    servings: "4",
    difficulty: "Easy",
    mode: "cook-in",
  },
  {
    id: "r15",
    name: "Chicken Parmesan",
    restaurant: "Home Kitchen",
    cuisine: "Italian",
    description: "Crispy breaded chicken, marinara, melted mozzarella, spaghetti, fresh basil",
    image: "https://images.unsplash.com/photo-1632778149955-e80f8ceca2e8?w=800&q=80",
    price: "$9",
    cookTime: "35 min",
    servings: "4",
    difficulty: "Easy",
    mode: "cook-in",
  },
  {
    id: "r16",
    name: "Pho Bo",
    restaurant: "Home Kitchen",
    cuisine: "Vietnamese",
    description: "Aromatic beef broth, rice noodles, rare beef slices, fresh herbs, bean sprouts",
    image: "https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?w=800&q=80",
    price: "$8",
    cookTime: "60 min",
    servings: "4",
    difficulty: "Hard",
    mode: "cook-in",
  },
  {
    id: "r17",
    name: "Shakshuka",
    restaurant: "Home Kitchen",
    cuisine: "Mediterranean",
    description: "Poached eggs in spiced tomato sauce, feta, herbs, crusty sourdough bread",
    image: "https://images.unsplash.com/photo-1590947132387-155cc02f3212?w=800&q=80",
    price: "$6",
    cookTime: "25 min",
    servings: "3",
    difficulty: "Easy",
    mode: "cook-in",
  },
  {
    id: "r18",
    name: "Beef Bulgogi Bowl",
    restaurant: "Home Kitchen",
    cuisine: "Korean",
    description: "Marinated beef, steamed rice, kimchi, sesame spinach, pickled vegetables",
    image: "https://images.unsplash.com/photo-1590301157890-4810ed352733?w=800&q=80",
    price: "$10",
    cookTime: "30 min",
    servings: "3",
    difficulty: "Medium",
    mode: "cook-in",
  },
  {
    id: "r19",
    name: "Chicken Alfredo",
    restaurant: "Home Kitchen",
    cuisine: "Italian",
    description: "Fettuccine, grilled chicken, creamy parmesan sauce, garlic bread, broccoli",
    image: "https://images.unsplash.com/photo-1645112411341-6c4fd023714a?w=800&q=80",
    price: "$8",
    cookTime: "25 min",
    servings: "4",
    difficulty: "Easy",
    mode: "cook-in",
  },
  {
    id: "r20",
    name: "Teriyaki Salmon Bowl",
    restaurant: "Home Kitchen",
    cuisine: "Japanese",
    description: "Glazed salmon, sushi rice, edamame, avocado, cucumber, sesame seeds",
    image: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800&q=80",
    price: "$12",
    cookTime: "25 min",
    servings: "2",
    difficulty: "Easy",
    mode: "cook-in",
  },
];

export function shuffleDishes(): Dish[] {
  return [...DISHES].sort(() => Math.random() - 0.5);
}

export function shuffleRecipes(): Dish[] {
  return [...RECIPES].sort(() => Math.random() - 0.5);
}
